name: graphview
description:  GraphView is used to display data in graph structures. It can display Tree layout, Directed and Layered graph. Useful for Family Tree, Hierarchy View.
version: 2.0.0
homepage: https://github.com/mihirpkshah/graphview
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
